### ISSUE TITLE
Feature Request: Skip to Next Song based on Waveform Level

### ISSUE THREAD

**Issue by PasttaTypo** [SPOTLAB-Live/Spicetify-waveform#2]
It would be so awesome if:
Once the playback point is in a silent part of a song at the end (for a specified time, default 1 or 2 sec.), the extension skips to the next track in queue so you don't play songs' large silent gaps. Could be customizable to auto-skip at an amount (0%-5% track volume)
Also since skipping via controls (like media keys or app buttons) overrides Spotify's cross-fade option, so tracks that have volume to the very end (like gapless album tracks) will cross-fade to the next track as normal.

**Comment by SPOTLAB-Live** [comment]
This extension is only meant to visualize the track and not so much the functionally that you describe. That is best suited for a new extension all together.
